-- items that are generated by quantum skills

local id = "Anti Personnel Mine"
CF_QuantumItems[#CF_QuantumItems + 1] = id
CF_QuantumItmPresets[id] = "Anti Personnel Mine"
CF_QuantumItmModules[id] = "Base.rte"
CF_QuantumItmClasses[id] = "TDExplosive"
CF_QuantumItmPrices[id] = 20

local id = "Remote Explosive"
CF_QuantumItems[#CF_QuantumItems + 1] = id
CF_QuantumItmPresets[id] = "Remote Explosive"
CF_QuantumItmModules[id] = "Base.rte"
CF_QuantumItmClasses[id] = "TDExplosive"
CF_QuantumItmPrices[id] = 25

local id = "Frag Grenade"
CF_QuantumItems[#CF_QuantumItems + 1] = id
CF_QuantumItmPresets[id] = "Frag Grenade"
CF_QuantumItmModules[id] = "Coalition.rte"
CF_QuantumItmClasses[id] = "TDExplosive"
CF_QuantumItmPrices[id] = 10

local id = "Cluster Grenade"
CF_QuantumItems[#CF_QuantumItems + 1] = id
CF_QuantumItmPresets[id] = "Cluster Grenade"
CF_QuantumItmModules[id] = "Coalition.rte"
CF_QuantumItmClasses[id] = "TDExplosive"
CF_QuantumItmPrices[id] = 20

local id = "Medikit"
CF_QuantumItems[#CF_QuantumItems + 1] = id
CF_QuantumItmPresets[id] = "Medikit"
CF_QuantumItmModules[id] = "Base.rte"
CF_QuantumItmClasses[id] = "HDFirearm"
CF_QuantumItmPrices[id] = 20